### ISSUE TITLE
Not working - disabling after few seconds

### ISSUE THREAD

**Issue by QsainBolt** [Alhxe/Discord-Integration#11]
**Paper 1.18.1**
**Discord bot setting in attachment**

[07:10:49] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[07:10:50] [ServerMain/INFO]: Reloading ResourceManager: Default, bukkit
[07:10:50] [Worker-Main-6/INFO]: Loaded 7 recipes
[07:10:53] [Server thread/INFO]: Starting minecraft server version 1.18.1
[07:10:53] [Server thread/INFO]: Loading properties
[07:10:53] [Server thread/INFO]: This server is running Paper version git-Paper-71 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 91f3eda)
[07:10:53] [Server thread/INFO]: Server Ping Player Sample Count: 12
[07:10:53] [Server thread/INFO]: Using 4 threads for Netty based IO
[07:10:53] [Server thread/INFO]: Default game type: SURVIVAL
[07:10:53] [Server thread/INFO]: Generating keypair
[07:10:53] [Server thread/INFO]: Starting Minecraft server on 172.27.232.2:18277
[07:10:53] [Server thread/INFO]: Using epoll channel type
[07:10:54] [Server thread/INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[07:10:54] [Server thread/INFO]: Paper: Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.
[07:10:55] [Server thread/INFO]: [LuckPerms] Loading LuckPerms v5.3.89
[07:10:55] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v7.2.8+6008-1246d61
[07:10:56] [Server thread/INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@7bd6d0d2]
[07:10:56] [Server thread/INFO]: [DICore] Loading DICore v2.0.4
[07:10:56] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[07:10:56] [Server thread/INFO]: [LuckPerms] Enabling LuckPerms v5.3.89
[07:10:57] [Server thread/INFO]: __
[07:10:57] [Server thread/INFO]: | |__) LuckPerms v5.3.89
[07:10:57] [Server thread/INFO]: |___ | Running on Bukkit - Paper
[07:10:57] [Server thread/INFO]:
[07:10:57] [Server thread/INFO]: [LuckPerms] Loading configuration...
[07:10:58] [Server thread/INFO]: [LuckPerms] Loading storage provider... [H2]
[07:10:58] [Server thread/INFO]: [LuckPerms] Loading internal permission managers...
[07:10:58] [Server thread/INFO]: [LuckPerms] Performing initial data load...
[07:10:59] [Server thread/INFO]: [LuckPerms] Successfully enabled. (took 2231ms)
[07:10:59] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v7.2.8+6008-1246d61
[07:10:59] [Server thread/INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[07:10:59] [Server thread/INFO]: WEPIF: Using the Bukkit Permissions API.
[07:10:59] [Server thread/INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.v1_18_R1.PaperweightAdapter as the Bukkit adapter
[07:11:01] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[07:11:01] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[07:11:01] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[07:11:01] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[07:11:01] [Server thread/INFO]: Preparing level "world"
[07:11:03] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[07:11:04] [Server thread/INFO]: Time elapsed: 449 ms
[07:11:04] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[07:11:04] [Server thread/INFO]: Time elapsed: 259 ms
[07:11:04] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[07:11:04] [Server thread/INFO]: Time elapsed: 249 ms
[07:11:04] [Server thread/INFO]: [DICore] Enabling DICore v2.0.4
[07:11:04] [Server thread/INFO]: [DICore] Plugin started
[07:11:04] [Server thread/ERROR]: Error occurred while enabling DICore v2.0.4 (Is it up to date?)
org.yaml.snakeyaml.error.YAMLException: java.nio.charset.MalformedInputException: Input length = 1
at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:218) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:176) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:171) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:126) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1198) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:308) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:248) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:213) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:155) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:140) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.Yaml.load(Yaml.java:429) ~[snakeyaml-1.28.jar:?]
at di.internal.controller.file.YamlManager.getYamlContent(YamlManager.java:85) ~[dicore-2.2.0.jar:?]
at di.internal.controller.file.YamlManager.(YamlManager.java:56) ~[dicore-2.2.0.jar:?]
at di.internal.controller.CoreController.(CoreController.java:57) ~[dicore-2.2.0.jar:?]
at di.dicore.BukkitApplication.onEnable(BukkitApplication.java:16) ~[dicore-2.2.0.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.18.1.jar:git-Paper-71]
at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.18.1.jar:git-Paper-71]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.1.jar:git-Paper-71]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-71]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-71]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-71]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-71]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.nio.charset.MalformedInputException: Input length = 1
at java.nio.charset.CoderResult.throwException(CoderResult.java:274) ~[?:?]
at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[?:?]
at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188) ~[?:?]
at java.io.InputStreamReader.read(InputStreamReader.java:177) ~[?:?]
at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:125) ~[snakeyaml-1.28.jar:?]
at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:183) ~[snakeyaml-1.28.jar:?]
... 28 more
[07:11:04] [Server thread/INFO]: [DICore] Disabling DICore v2.0.4
[07:11:04] [Server thread/INFO]: [DICore] Plugin disabled
[07:11:05] [Server thread/INFO]: Starting remote control listener
[07:11:05] [Server thread/INFO]: Thread RCON Listener started
[07:11:05] [Server thread/INFO]: RCON running on 172.27.232.2:38277
[07:11:05] [Server thread/INFO]: Running delayed init tasks
[07:11:05] [Server thread/INFO]: Done (11.998s)! For help, type "help"
[07:11:05] [Server thread/INFO]: Timings Reset

![issue1](https://user-images.githubusercontent.com/21966950/146135015-f5749045-c8b4-4a65-bf3b-6593c8218068.jpg)
![issue2](https://user-images.githubusercontent.com/21966950/146135009-02fd33b6-1c30-4c91-8961-54f13822815f.jpg)

**Comment by QsainBolt** [comment]
Ok, I repaired my fault.

Now I have a problem, because bot won't write to us (on discord) to confirmation registration. 
I pasted my discord ID (example: '/register abcd#1234'), but plugin called that user is not found.

Edit:
I pasted wrong ID. Now plugin works perfectly! ❤
