### ISSUE TITLE
DILogin does not load

### ISSUE THREAD

**Issue by candied-apple** [Alhxe/Discord-Integration#14]
[18:39:19 INFO]: [DILogin] Enabling DILogin v3.4.0
[18:39:19 INFO]: [DILogin] Plugin started
[18:39:19 ERROR]: Error occurred while enabling DILogin v3.4.0 (Is it up to date?)
org.yaml.snakeyaml.scanner.ScannerException: while scanning for the next token
found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
in 'reader', line 59, column 1:
#EXAMPLE
^

at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:460) ~[Simple-Yaml-1.8.jar:?]
at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:251) ~[Simple-Yaml-1.8.jar:?]
at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:628) ~[Simple-Yaml-1.8.jar:?]
at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:166) ~[Simple-Yaml-1.8.jar:?]
at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59) ~[Simple-Yaml-1.8.jar:?]
at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45) ~[Simple-Yaml-1.8.jar:?]
at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140) ~[Simple-Yaml-1.8.jar:?]
at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119) ~[Simple-Yaml-1.8.jar:?]
at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:214) ~[Simple-Yaml-1.8.jar:?]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:184) ~[Simple-Yaml-1.8.jar:?]
at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314) ~[Simple-Yaml-1.8.jar:?]
at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305) ~[Simple-Yaml-1.8.jar:?]
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286) ~[Simple-Yaml-1.8.jar:?]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188) ~[Simple-Yaml-1.8.jar:?]
at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:245) ~[Simple-Yaml-1.8.jar:?]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:186) ~[Simple-Yaml-1.8.jar:?]
at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314) ~[Simple-Yaml-1.8.jar:?]
at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305) ~[Simple-Yaml-1.8.jar:?]
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286) ~[Simple-Yaml-1.8.jar:?]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188) ~[Simple-Yaml-1.8.jar:?]
at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115) ~[Simple-Yaml-1.8.jar:?]
at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:142) ~[Simple-Yaml-1.8.jar:?]
at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151) ~[Simple-Yaml-1.8.jar:?]
at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:491) ~[Simple-Yaml-1.8.jar:?]
at org.yaml.snakeyaml.Yaml.load(Yaml.java:429) ~[Simple-Yaml-1.8.jar:?]
at di.internal.controller.file.ConfigManager.<init>(ConfigManager.java:38) ~[dicore-2.4.0.jar:?]
at di.internal.controller.InternalController.<init>(InternalController.java:54) ~[dicore-2.4.0.jar:?]
at di.dicore.DIApi.<init>(DIApi.java:44) ~[dicore-2.4.0.jar:?]
at di.dilogin.BukkitApplication.connectWithCoreApi(BukkitApplication.java:103) ~[dilogin-3.4.0.jar:?]
at di.dilogin.BukkitApplication.onEnable(BukkitApplication.java:49) ~[dilogin-3.4.0.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:309) ~[PlugManX.jar:?]
at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:267) ~[PlugManX.jar:?]
at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:393) ~[PlugManX.jar:?]
at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) ~[PlugManX.jar:?]
at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[PlugManX.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:946) ~[purpur-1.19.jar:git-Purpur-1684]
at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchServerCommand(CraftServer.java:909) ~[purpur-1.19.jar:git-Purpur-1684]
at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:512) ~[purpur-1.19.jar:git-Purpur-1684]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.jar:git-Purpur-1684]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1441) ~[purpur-1.19.jar:git-Purpur-1684]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1208) ~[purpur-1.19.jar:git-Purpur-1684]
at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1684]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:39:19 INFO]: [DILogin] Disabling DILogin v3.4.0

**Comment by candied-apple** [comment]
![image](https://user-images.githubusercontent.com/50497574/175825452-a4e7956b-d6cb-463c-b870-14b67682fd79.png)
i find a solution
in the auto generated dilogin/config.yml file we just need to delete the spaces as i show in the image 
Could u fix the auto generated config file

**Comment by candied-apple** [comment]
### **Now every time i join server i get an error like this and react to login funciton does not work.**

[19:13:38 ERROR]: [net.dv8tion.jda.api.JDA] One of the EventListeners had an uncaught exception
java.lang.NoClassDefFoundError: net/dv8tion/jda/api/events/message/react/MessageReactionAddEvent
at di.dilogin.discord.event.UserReactionMessageEvent.onMessageReactionAdd(UserReactionMessageEvent.java:40) ~[dilogin-3.4.0.jar:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:411) ~[dicore-2.4.0.jar:?]
at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96) ~[dicore-2.4.0.jar:?]
at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88) ~[dicore-2.4.0.jar:?]
at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70) ~[dicore-2.4.0.jar:?]
at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:149) ~[dicore-2.4.0.jar:?]
at net.dv8tion.jda.internal.handle.MessageReactionHandler.onAdd(MessageReactionHandler.java:187) ~[dicore-2.4.0.jar:?]
at net.dv8tion.jda.internal.handle.MessageReactionHandler.handleInternally(MessageReactionHandler.java:159) ~[dicore-2.4.0.jar:?]
at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36) ~[dicore-2.4.0.jar:?]
at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952) ~[dicore-2.4.0.jar:?]
at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839) ~[dicore-2.4.0.jar:?]
at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817) ~[dicore-2.4.0.jar:?]
at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:990) ~[dicore-2.4.0.jar:?]
at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[dicore-2.4.0.jar:?]
at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[dicore-2.4.0.jar:?]
at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[dicore-2.4.0.jar:?]
at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[dicore-2.4.0.jar:?]
at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[dicore-2.4.0.jar:?]
at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[dicore-2.4.0.jar:?]
at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[dicore-2.4.0.jar:?]
[19:13:43 ERROR]: [net.dv8tion.jda.api.JDA] One of the EventListeners had an uncaught exception
java.lang.NoClassDefFoundError: net/dv8tion/jda/api/events/message/react/MessageReactionAddEvent
at di.dilogin.discord.event.UserReactionMessageEvent.onMessageReactionAdd(UserReactionMessageEvent.java:40) ~[dilogin-3.4.0.jar:?]
at jdk.internal.reflect.GeneratedMethodAccessor81.invoke(Unknown Source) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:411) ~[dicore-2.4.0.jar:?]
at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96) ~[dicore-2.4.0.jar:?]
at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88) ~[dicore-2.4.0.jar:?]
at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70) ~[dicore-2.4.0.jar:?]
at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:149) ~[dicore-2.4.0.jar:?]
at net.dv8tion.jda.internal.handle.MessageReactionHandler.onAdd(MessageReactionHandler.java:187) ~[dicore-2.4.0.jar:?]
at net.dv8tion.jda.internal.handle.MessageReactionHandler.handleInternally(MessageReactionHandler.java:159) ~[dicore-2.4.0.jar:?]
at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36) ~[dicore-2.4.0.jar:?]
at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952) ~[dicore-2.4.0.jar:?]
at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839) ~[dicore-2.4.0.jar:?]
at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817) ~[dicore-2.4.0.jar:?]
at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:990) ~[dicore-2.4.0.jar:?]
at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[dicore-2.4.0.jar:?]
at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[dicore-2.4.0.jar:?]
at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[dicore-2.4.0.jar:?]
at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[dicore-2.4.0.jar:?]
at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[dicore-2.4.0.jar:?]
at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[dicore-2.4.0.jar:?]
at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[dicore-2.4.0.jar:?]

**Comment by Alhxe** [comment]
Solved in 2.4.1 version
