### ISSUE TITLE
an error in the console, I can't figure out what's wrong

### ISSUE THREAD

**Issue by forditt** [Alhxe/Discord-Integration#21]
[16:29:36 ERROR]: Could not pass event DILoginEvent to DILogin v4.0.1-beta1
java.lang.NumberFormatException: The specified ID is not a valid snowflake (discord_rol_id). Expecting a valid long value!
	at net.dv8tion.jda.api.utils.MiscUtil.parseSnowflake(MiscUtil.java:123) ~[dicore-4.0.1.jar:?]
	at net.dv8tion.jda.api.utils.cache.SnowflakeCacheView.getElementById(SnowflakeCacheView.java:59) ~[dicore-4.0.1.jar:?]
	at net.dv8tion.jda.api.entities.Guild.getRoleById(Guild.java:2068) ~[dicore-4.0.1.jar:?]
	at di.dilogin.minecraft.ext.luckperms.LuckPermsController.lambda$syncUserRole$1(LuckPermsController.java:94) ~[dilogin-4.0.1.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at di.dilogin.minecraft.ext.luckperms.LuckPermsController.syncUserRole(LuckPermsController.java:84) ~[dilogin-4.0.1.jar:?]
	at di.dilogin.minecraft.ext.luckperms.LuckPermsLoginBukkitEvent.onLogin(LuckPermsLoginBukkitEvent.java:25) ~[dilogin-4.0.1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor86.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:git-Purpur-1886]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:680) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at di.dilogin.controller.impl.DILoginControllerBukkitImpl.lambda$loginUser$0(DILoginControllerBukkitImpl.java:91) ~[dilogin-4.0.1.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.3.jar:git-Purpur-1886]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.3.jar:git-Purpur-1886]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.3.jar:git-Purpur-1886]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:482) ~[purpur-1.19.3.jar:git-Purpur-1886]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.3.jar:git-Purpur-1886]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1886]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1886]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by forditt** [comment]
I thought it was because of the core, changed it and nothing changed


[16:34:10 ERROR]: Could not pass event DILoginEvent to DILogin v4.0.1-beta1
java.lang.NumberFormatException: The specified ID is not a valid snowflake (discord_rol_id). Expecting a valid long value!
	at net.dv8tion.jda.api.utils.MiscUtil.parseSnowflake(MiscUtil.java:123) ~[dicore-4.0.1.jar:?]
	at net.dv8tion.jda.api.utils.cache.SnowflakeCacheView.getElementById(SnowflakeCacheView.java:59) ~[dicore-4.0.1.jar:?]
	at net.dv8tion.jda.api.entities.Guild.getRoleById(Guild.java:2068) ~[dicore-4.0.1.jar:?]
	at di.dilogin.minecraft.ext.luckperms.LuckPermsController.lambda$syncUserRole$1(LuckPermsController.java:94) ~[dilogin-4.0.1.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at di.dilogin.minecraft.ext.luckperms.LuckPermsController.syncUserRole(LuckPermsController.java:84) ~[dilogin-4.0.1.jar:?]
	at di.dilogin.minecraft.ext.luckperms.LuckPermsLoginBukkitEvent.onLogin(LuckPermsLoginBukkitEvent.java:25) ~[dilogin-4.0.1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor84.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-371]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at di.dilogin.controller.impl.DILoginControllerBukkitImpl.lambda$loginUser$0(DILoginControllerBukkitImpl.java:91) ~[dilogin-4.0.1.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-371]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.3.jar:git-Paper-371]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.3.jar:git-Paper-371]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:440) ~[paper-1.19.3.jar:git-Paper-371]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-371]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-371]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-371]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Alhxe** [comment]
Hello,
The bug is already fixed in the beta of the next version. Attached in case you want to use it while finishing the final version now i can give u on discord. 

https://discord.gg/7t28cPFj

**Comment by forditt** [comment]
Got it, thank you very much for your reply

**Comment by Alhxe** [comment]
https://github.com/Alhxe/Discord-Integration/releases/tag/4.0.2
