### ISSUE TITLE
why is di login taking  class net.dv8tion.jda.api.entities.User from MinecraftDiscordAnnouncer v1.0 ?

### ISSUE THREAD

**Issue by Grandminecraft** [Alhxe/Discord-Integration#24]
[13:20:53] [Server thread/INFO]: [DILogin] Enabling DILogin v4.0.3
[13:20:53] [Server thread/INFO]: [DILogin] DICore has successfully connected with DILogin
[13:20:53] [Server thread/WARN]: [DILogin] Loaded class net.dv8tion.jda.api.entities.User from MinecraftDiscordAnnouncer v1.0 which is not a depend or softdepend of this plugin.
[13:20:53] [Server thread/INFO]: [DILogin] Database connection type: SQLITE
[13:20:53] [Server thread/ERROR]: Error occurred while enabling DILogin v4.0.3 (Is it up to date?)
java.lang.IllegalArgumentException: Listener must implement EventListener
        at net.dv8tion.jda.api.hooks.InterfacedEventManager.register(InterfacedEventManager.java:62) ~[?:?]
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.register(EventManagerProxy.java:53) ~[?:?]
        at net.dv8tion.jda.internal.JDAImpl.addEventListener(JDAImpl.java:826) ~[?:?]
        at di.dicore.api.impl.DIApiBukkitImpl.registerDiscordEvent(DIApiBukkitImpl.java:61) ~[?:?]
        at di.dilogin.BukkitApplication.initDiscordEvents(BukkitApplication.java:202) ~[?:?]
        at di.dilogin.BukkitApplication.onEnable(BukkitApplication.java:68) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:539) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3652-Spigot-19641c7-6aeb5e4]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:453) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3652-Spigot-19641c7-6aeb5e4]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:587) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3652-Spigot-19641c7-6aeb5e4]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:412) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3652-Spigot-19641c7-6aeb5e4]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3652-Spigot-19641c7-6aeb5e4]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3652-Spigot-19641c7-6aeb5e4]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:301) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3652-Spigot-19641c7-6aeb5e4]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:20:53] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[13:20:53] [Server thread/INFO]: Done (25.772s)! For help, type "help"
Skynode: Server marked as running...
[13:20:53] [Craft Scheduler Thread - 1/INFO]: [Vault] Checking for Updates ... 
[13:20:53] [Craft Scheduler Thread - 1/INFO]: [Vault] No new version available
Skynode: Server marked as running...
[13:12:11] [Craft Scheduler Thread - 0/INFO]: [Vault] Checking for Updates ... 
[13:12:11] [Craft Scheduler Thread - 0/INFO]: [Vault] No new version available

**Comment by Alhxe** [comment]
problem is that plugin is using JDA (is the discord api) and they're using older version of JDA
