### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by forditt** [Alhxe/Discord-Integration#30]
A strange error in the console after which the plugin crashes:
```
[15:32:03 ERROR]: Could not pass event PlayerJoinEvent to DILogin v4.1.0
net.dv8tion.jda.api.exceptions.ErrorResponseException: 10007: Unknown Member
        at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:227) ~[dicore-4.1.0-noslf4j.jar:?]
        at net.dv8tion.jda.internal.requests.DeferredRestAction.complete(DeferredRestAction.java:172) ~[dicore-4.1.0-noslf4j.jar:?]
        at net.dv8tion.jda.api.requests.RestAction.complete(RestAction.java:633) ~[dicore-4.1.0-noslf4j.jar:?]
        at di.dilogin.controller.DILoginController.syncUserName(DILoginController.java:167) ~[dilogin-4.1.0.jar:?]
        at di.dilogin.minecraft.bukkit.event.impl.UserLoginInternEventImpl.onPlayerJoin(UserLoginInternEventImpl.java:64) ~[dilogin-4.1.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor175.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-1995]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:339) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:202) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:183) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:85) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:608) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1602) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1421) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: net.dv8tion.jda.api.exceptions.ContextException
        at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54) ~[dicore-4.1.0-noslf4j.jar:?]
        at net.dv8tion.jda.api.requests.Request.<init>(Request.java:71) ~[dicore-4.1.0-noslf4j.jar:?]
        at net.dv8tion.jda.api.requests.RestFuture.<init>(RestFuture.java:36) ~[dicore-4.1.0-noslf4j.jar:?]
        at net.dv8tion.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:209) ~[dicore-4.1.0-noslf4j.jar:?]
        at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:219) ~[dicore-4.1.0-noslf4j.jar:?]
        ... 23 more
```

**Comment by Alhxe** [comment]
It looks like a bug in the name synchronization module. If you experience this problem a lot, you can temporarily disable it until it is fixed

**Comment by forditt** [comment]
Ok, thanks for the reply

**Comment by forditt** [comment]
Why are player names synchronized only after the server is restarted and when the player logs in again? It seemed to me that the nickname should be synchronized immediately, or everything was intended that way?

**Comment by Alhxe** [comment]
The name is changed when you log in to the server. This is done to avoid overloading the plugin with repetitive tasks.
