### ISSUE TITLE
DILogin not working on 1.17.1

### ISSUE THREAD

**Issue by LosBagros** [Alhxe/Discord-Integration#4]
```
[08:44:09 INFO]: [DICore] Enabling DICore v2.0.4
[08:44:09 INFO]: [DICore] Plugin started
[08:44:09 INFO]: [DICore] Starting Bot
[08:44:11 INFO]: [net.dv8tion.jda.api.JDA] Login Successful!
[08:44:12 INFO]: [net.dv8tion.jda.internal.requests.WebSocketClient] Connected to WebSocket
[08:44:13 ERROR]: [net.dv8tion.jda.internal.requests.WebSocketClient] WebSocket connection was closed and cannot be recovered due to identification issues
CloseCode(4014 / Disallowed intents. Your bot might not be eligible to request a privileged intent such as GUILD_PRESENCES or GUILD_MEMBERS.)
[08:44:13 ERROR]: Error occurred while enabling DICore v2.0.4 (Is it up to date?)
java.lang.IllegalStateException: Was shutdown trying to await status
        at net.dv8tion.jda.internal.JDAImpl.awaitStatus(JDAImpl.java:452) ~[?:?]
        at net.dv8tion.jda.api.JDA.awaitStatus(JDA.java:310) ~[?:?]
        at net.dv8tion.jda.api.JDA.awaitReady(JDA.java:360) ~[?:?]
        at di.internal.entity.DiscordBot.initBot(DiscordBot.java:69) ~[?:?]
        at di.internal.entity.DiscordBot.<init>(DiscordBot.java:56) ~[?:?]
        at di.internal.controller.CoreController.initBot(CoreController.java:87) ~[?:?]
        at di.internal.controller.CoreController.<init>(CoreController.java:58) ~[?:?]
        at di.dicore.BukkitApplication.onEnable(BukkitApplication.java:16) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Paper-110]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-110]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-110]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.1.jar:git-Paper-110]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.1.jar:git-Paper-110]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639) ~[patched_1.17.1.jar:git-Paper-110]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[patched_1.17.1.jar:git-Paper-110]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-110]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-110]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[08:44:13 INFO]: [DICore] Disabling DICore v2.0.4
[08:44:13 INFO]: [DICore] Plugin disabled
[08:44:13 INFO]: [DILogin] Enabling DILogin v3.0.6
[08:44:13 INFO]: [DILogin] Plugin started
[08:44:13 ERROR]: Error occurred while enabling DILogin v3.0.6 (Is it up to date?)
java.lang.NoClassDefFoundError: di/dicore/DIApi
        at di.dilogin.BukkitApplication.connectWithCoreApi(BukkitApplication.java:97) ~[?:?]
        at di.dilogin.BukkitApplication.onEnable(BukkitApplication.java:44) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Paper-110]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-110]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-110]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.1.jar:git-Paper-110]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.1.jar:git-Paper-110]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639) ~[patched_1.17.1.jar:git-Paper-110]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[patched_1.17.1.jar:git-Paper-110]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-110]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-110]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: di.dicore.DIApi
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146) ~[patched_1.17.1.jar:git-Paper-110]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-110]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 12 more
[08:44:13 INFO]: [DILogin] Disabling DILogin v3.0.6
```

**Comment by Alhxe** [comment]
You have to enable discord privileged intents in developer portal.

**Comment by LosBagros** [comment]
Thanks, now it is working.
